### ISSUE TITLE
Add checklist to bug report and feature request templates

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#670]
### Feature request is related to

- [Bug report and feature request templates](https://github.com/davidjerleke/embla-carousel/tree/master/.github/ISSUE_TEMPLATE)

### Is your feature request related to an issue?

- We need to encourage devs to **search for existing issues** and read the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md) before creating issues. I get too many issues with missing details and test cases which is time consuming.

### Describe the solution you'd like

Add the following checkboxes to the templates:

- [ ] I’ve made research efforts 
- [ ] I've searched for existing issues
- [ ] I've read the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md)

**Comment by smultar** [comment]
You should consider mimicking how **NextJs** runs their bug reports. Check out [this](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)

It is a better experience in my opinion than the standard rich text editor and may force people to produce reports more towards the format you're looking for.

![image](https://github.com/davidjerleke/embla-carousel/assets/6223536/91ee6f06-bb4e-45da-8f30-08f1ac04a2c4)

Even has dropdowns to select specific issues.

![image](https://github.com/davidjerleke/embla-carousel/assets/6223536/dbb147ab-59d9-43cc-b880-3889c8b0abe4)

**Comment by smultar** [comment]
Hey @davidjerleke, I decided to take a step forward and assist by making [a fork](https://github.com/smultar/embla-carousel) of the project and making a new issue template for you. Let me know if you need any more additional changes.

I love the work you do and know what it is like maintaining projects. Thought I would do my part.
![image](https://github.com/davidjerleke/embla-carousel/assets/6223536/f0c02679-deb1-493b-acd7-d5b9cb4444f2)

**Comment by davidjerleke** [comment]
@smultar I didn’t know this existed. Thanks a lot for the idea and the PR. This makes a lot of sense 👍🏻.

**Comment by smultar** [comment]
If you need me to do anything, feel free to reach out. I don't mind throwing a helping hand. 

If you use Discord, feel free to add me there. My handle is `smultar`
